name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

     - name: Configurar ambiente
       run: echo "Ambiente configurado com sucesso!"

    - name: Executar tarefa simples
      run: echo "Teste executado com sucesso!"
